service: xyzreality

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  # - serverless-dotenv-plugin # not use in this test

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  # environment:  # not use in this test
  #   envVar: ${env:ENV_VAR}

functions:
  health:
    handler: src/handlers/health.check
    events:
      - http:
          path: health
          method: get
  userGet:
    handler: "src/handlers/user.userGet"
    events:
      - http:
          path: user
          method: get
